## Problem Statement

Q.1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
def compute():
      x = 5/0

try:
   compute()

except:
    print("divisible by zero error")

divisible by zero error


Q.2 Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

    Hint: Subject,Verb and Object should be declared in the program as shown below.
    subjects=["Americans ","Indians"]
    verbs=["play","watch"]
    objects=["Baseball","Cricket"]

    Output should come as below:
    Americans play Baseball.
    Americans play Cricket.
    Americans watch Baseball.
    Americans watch Cricket.
    Indians play Baseball.
    Indians play Cricket.
    Indians watch Baseball.
    Indians watch Cricket.

In [3]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

list1 = [(sub+" "+ vb + " " + obj) for sub in subjects for vb in verbs for obj in objects]
for pattern in list1:
    print(pattern)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Q.3 Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

    HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.

In [1]:
import numpy as np

def gen_matrix(inputpvector, n, increasing=False):
    if not increasing:
        output_matx = np.array([x ** (n - 1 - i) for x in inputpvector for i in range(n)]).reshape(inputpvector.size, n)
    elif increasing:
        output_matx = np.array([x ** i for x in inputpvector for i in range(n)]).reshape(inputpvector.size, n)

    return output_matx

inputvector = np.array([1,2,3,4,5])
output_mat_cols = 5
output_matx_decreasing = gen_matrix(inputvector,output_mat_cols,False)
output_matx_increasing= gen_matrix(inputvector,output_mat_cols,True)


print("The input Vector is:",inputvector,"\n")
print("Number of columns in output matrix are:",output_mat_cols,"\n")
print("Vander matrix of the input array in decreasing order of powers is:\n\n",output_matx_decreasing,"\n")
print("Vander matrix of the input array in increasing order of powers is:\n\n",output_matx_increasing,"\n")

The input Vector is: [1 2 3 4 5] 

Number of columns in output matrix are: 5 

Vander matrix of the input array in decreasing order of powers is:

 [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]] 

Vander matrix of the input array in increasing order of powers is:

 [[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]] 

