# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [9]:
import numpy as np
a=6*np.ones((5,5))
print("Expected OutputOriginal array is:\n")
print(a,"\n")

for i in range(1,4):
    for j in range(1,4):
        a[i,j] = 0
print("6 on the border and 0 inside in the array is:\n")
print(a)

Expected OutputOriginal array is:

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]] 

6 on the border and 0 inside in the array is:

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [7]:
b=9*np.ones((8,8))

for i in range(0,8):
    for j in range(0,8):
        if(i%2==0) and (j%2==0):
            b[i][j]=3

for k in range(0, 8):
    for l in range(0,8):
        if(k%2!=0) and (l%2!=0):
            b[l][k]=3

print("checkerboard pattern of size 8X8 is:\n")
print(b)

checkerboard pattern of size 8X8 is:

[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [6]:
import numpy as np

x = np.empty((3,4))
print("Empty array of size 3X4 is:\n")
print(x,"\n")

print("Full array of size 3X3 is:\n")
y = np.full((3,3),6)
print(y)

Empty array of size 3X4 is:

[[3.56043053e-307 1.60219306e-306 7.56571288e-307 1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 1.60218763e-306 1.69121367e-306]
 [8.01097889e-307 1.33512308e-306 9.79103798e-307 1.24610927e-306]] 

Full array of size 3X3 is:

[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [12]:
lst=[0, 12, 45.21 ,34, 99.91]
faran_values=np.array(lst)
print("Given Faranheit values are:")
print(faran_values)

print("Centigrade values of corresponding faranheit values are:")
print(5*(faran_values/9 - 32/9))

Given Faranheit values are:
[ 0.   12.   45.21 34.   99.91]
Centigrade values of corresponding faranheit values are:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [15]:
lst1=[ 1.00000000+0.j ,0.70710678+0.70710678j]
arr=np.array(lst1)
print("Given array is:")
print(arr,"\n")
print("Real part of the array is:")
print(arr.real,"\n")

print("Imaginary part of the array is:")
print(arr.imag)

Given array is:
[1.        +0.j         0.70710678+0.70710678j] 

Real part of the array is:
[1.         0.70710678] 

Imaginary part of the array is:
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [19]:
arr1=np.array([ 0,10,20,40,60])
arr2=np.array([0,40])
print("Comparing each element of arr1 and arr2:\n")
print(np.in1d(arr1, arr2))

Comparing each element of arr1 and arr2:

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [20]:
arr3=np.array([ 0, 10, 20, 40, 60])
arr4=np.array([ 10, 30, 40])
print("common values between arr3 and arr4 are:\n")
print(np.intersect1d(arr3,arr4))

common values between arr3 and arr4 are:

[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [21]:
arr5=np.array([10, 10, 20, 20, 30, 30])
print("Given array is:",arr5)
print("\nUnique elements of the above array are:\n")
print(np.unique(arr5))

arr6=np.array([[1,1],[2,3]])
print("Given array is: \n",arr6)
print("\nUnique elements of the above array are:\n")
print(np.unique(arr6))

Given array is: [10 10 20 20 30 30]

Unique elements of the above array are:

[10 20 30]
Given array is: 
 [[1 1]
 [2 3]]

Unique elements of the above array are:

[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [23]:
arr7=np.array([0,10,20,40,60,80])
arr8=np.array([10,30,40,50,70])

print("First array is:",arr7)
print("\nSecond array is:",arr8)

print("\n Unique values that are in only one (not both) of the input arrays are:")
print(np.setxor1d(arr7, arr8))

First array is: [ 0 10 20 40 60 80]

Second array is: [10 30 40 50 70]

 Unique values that are in only one (not both) of the input arrays are:
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [25]:
arr9=np.array([1,0,3,5,-6,0,3,2,0,-10])
l=len(arr9)
print("Prints True if value is not zero, if zero prints False \n ")
for i in range(l):
    if arr9[i]==0:
        print(False,end=" ")
    else:
        print(True,end=" ")

Prints True if value is not zero, if zero prints False 
 
True False True True True False True True False True 

In [30]:

print(np.all([[True,True],[True,True]]))
print(np.all([[True,False],[True,True]]))

print("\n")
print(np.all([5, 27, -15, 0]))
print(np.all([-10,  45]))

True
False


False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [38]:
print(np.all([[True,False],[True,True]], axis = 0))

print(np.all([[True,False],[True,True]], axis=1))


print("\n")
print(np.all([[5, 27, -15],[4,0,-2]],axis = 0))
print(np.all([[-10,  45],[0,34]],axis = 1))

[ True False]
[False  True]


[ True False  True]
[ True False]


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [41]:
sam_array=np.array([1, 2, 3, 4])
print("given array is:",sam_array)
print("\n")

print("Printing twice:\n")
print(np.tile(sam_array,2))

print("\n")
print("Printing thrice:\n")
print(np.tile(sam_array,3))

given array is: [1 2 3 4]


Printing twice:

[1 2 3 4 1 2 3 4]


Printing thrice:

[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [42]:
org_arr=np.array([1,2,3,4,5,6])
print("Given arry:",org_arr)

print("Maximum Values: ",np.argmax(org_arr))
print("Minimum Values: ",np.argmin(org_arr))

Given arry: [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [43]:
first_arr = np.array([1, 2])
second_arr = np.array([4, 5])
print("First Array : ",first_arr)
print("Second Array : ",second_arr)
print("\n")
print("First Array > Second Array")
print(np.greater(first_arr, second_arr))
print("\n")
print("First Array >= Second Array")
print(np.greater_equal(first_arr, second_arr))
print("\n")
print("First Array < Second Array")
print(np.less(first_arr, second_arr))
print("\n")
print("First Array <= Second Array")
print(np.less_equal(first_arr, second_arr))

First Array :  [1 2]
Second Array :  [4 5]


First Array > Second Array
[False False]


First Array >= Second Array
[False False]


First Array < Second Array
[ True  True]


First Array <= Second Array
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [44]:
array1=np.array([[4,6],[2,1]])
print("The given array is:\n",array1)
print("\n")
print("Sort along the first axis: ")
array1_x=np.sort(array1,axis=0)
print(array1_x)
print("\n")
print("Sort along the last axis: ")
array1_y=np.sort(array1_x,axis=1)
print(array1_y)

The given array is:
 [[4 6]
 [2 1]]


Sort along the first axis: 
[[2 1]
 [4 6]]


Sort along the last axis: 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [48]:
first_names = ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names =('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

fnames=np.array(first_names)
lnames=np.array(last_names)

print("Given First names are:\n",fnames)
print("\n")

print("Given Last names are:\n",lnames)
print("\n")

f_n = np.lexsort((fnames, lnames))
print("sorting indices of given arrays is:",f_n)

Given First names are:
 ['Margery' 'Betsey' 'Shelley' 'Lanell' 'Genesis']


Given Last names are:
 ['Woolum' 'Battle' 'Plotner' 'Brien' 'Stahl']


sorting indices of given arrays is: [1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [50]:
arr_org=np.array([[0,10,20],[20,30,40]])
print("The given array is:\n")
print(arr_org)
print("\n")

output=arr_org[arr_org>10]
print("The elements bigger than 10 are:",output)
print("\n")

print("The index vaules of elements", output,"which are greater than 10 are:",np.nonzero(arr_org > 10))

The given array is:

[[ 0 10 20]
 [20 30 40]]


The elements bigger than 10 are: [20 20 30 40]


The index vaules of elements [20 20 30 40] which are greater than 10 are: (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [63]:
num_arr=np.identity(4)
print("The identity matrix of given size is:\n", num_arr)
print("\n")
print("Given array size is:",num_arr.size)
print("\n")
print("Item size in given array is:",num_arr.itemsize)
print("\n")
print("memory size of given array is:")
print( (num_arr.size * num_arr.itemsize),"bytes")

The identity matrix of given size is:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Given array size is: 16


Item size in given array is: 8


memory size of given array is:
128 bytes


## Great Job!